### ISSUE TITLE
Self intersection in hybrid

### ISSUE THREAD

**Issue by Nielsbishere** [TeamWisp/WispRenderer#239] opened 2019-04-04 14:44 UTC
**Describe the bug**
Hybrid reconstructs world position from depth buffer, this ends up into a lot of precision loss. This means that bigger scenes have more self intersection.

**To Reproduce**
Go to emibl with the epsilon value of 0.01 (or something small). Raytracing will look correct, but hybrid won't.

**Expected behaviour**
Hybrid should look identical to raytracing.

**Screenshots**
Don't have RTX screenshots, but classic self intersection (black lines and artifacts when moving the screen around, disappear or get less when you get closer).

**Desktop (please complete the following information):**
Tower

**Additional context**
N.A.

**Comment by VZout** [comment] 2019-05-06 09:34
Closing for now. Its planned and not really a bug since it is expected behavior.

**Closed by VZout** 2019-05-06 09:34 UTC
Labels: bug
