### ISSUE TITLE
Switching frame graphs after resizing breaks.

### ISSUE THREAD

**Issue by DBouma** [TeamWisp/WispRenderer#300] opened 2019-05-16 08:39 UTC
**Describe the bug**
On initially changing frame graphs for example deferred -> hybrid, after having changed the resolution of the window. Wisp crashes on memcpy, after the acceleration structures are being uploaded.

**To Reproduce**
Steps to reproduce the behaviour:
1. Swap to master branch
2. Launch default wisp renderer (viknell scene)
3. Resize window to any resolution
4. press "F2" to switch from deferred to hybrid
5. Enjoy the crash.

**Expected behaviour**
Wisp switches to hybrid at new resolution without crashing.

**Desktop (please complete the following information):**
- GTX 980m
- Fallback layer.

**Additional context**

**Comment by LaisoEmilio** [comment] 2019-05-17 08:04
Tested on RTX, resizing then switching to hybrid showed black pattern artefacts on the final render and then crashed once I tried resizing after

**Comment by VZout** [comment] 2019-05-27 08:53
I am unable to reproduce this.

**Comment by VZout** [comment] 2019-05-27 08:54
other pr fixed this, closing issue.

**Closed by VZout** 2019-05-27 08:54 UTC
Labels: bug
